### ISSUE TITLE
solo升级到最新版本后，部分主题加载失败

### ISSUE THREAD

**Issue by snowfigure** [b3log/solo-skins#18]
solo升级到了 Solo 2.9.4（自编译，同步github上solo最新的代码库，JDK 8，Tomcat + Nginx方式部署）。
无论是数据库是用的 Solo 2.9.3的数据库，还是全新部署

切换某些主题后，查看首页报错，报错信息如下：

	[ERROR]-[2018-09-21 15:18:46]-[org.b3log.latke.servlet.renderer.freemarker.AbstractFreeMarkerRenderer:138]: FreeMarker renders error
	FreeMarker template error:
	An error has occurred when reading existing sub-variable "articleUpdateDate"; see cause exception! The type of the containing value was: extended_hash+string (org.json.JSONObject wrapped into f.e.b.StringModel)
	----
	FTL stack trace ("~" means nesting-related):
		- Failed at: ${article.articleUpdateDate?string("y...  [in template "article-list.ftl" at line 26, column 17]
		- Reached through: #include "article-list.ftl"  [in template "index.ftl" at line 41, column 21]
	----
	Java stack trace (for programmers):
	----
	freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]

	.....

	Caused by: org.json.JSONException: JSONObject["articleUpdateDate"] not found.
		at org.json.JSONObject.get(JSONObject.java:540)
		... 67 more

另外的问题是：我吧amaze的主题放在skins目录下，并没有扫到amaze这个主题包。

**Comment by 88250** [comment]
请发一下主题名。

**Comment by snowfigure** [comment]
Community、classic、NeoEase、Andrea、metro-hot

以上主题会报错。

另外的问题是：我把amaze的主题放在skins目录下，并没有扫到amaze这个主题包（在2.9.3的版本下没有问题）。

**Comment by 88250** [comment]
你下载最新的 war 或者用 master 编译一个最新的试试。

**Comment by snowfigure** [comment]
> 你下载最新的 war 或者用 master 编译一个最新的试试。

那我试一试直接从你们的master库上下载一份，搞一下试一试

**Comment by 88250** [comment]
好的，我先关闭 issue 了，有问题更贴就行。
