### ISSUE TITLE
nijigen皮肤从文章列表进入文章，滚动条没有在顶部

### ISSUE THREAD

**Issue by zwxbest** [b3log/solo-skins#21]
浏览文章列表，滚动条不在顶部时，点击进入文章，滚动条没有在最顶部。有的在中部，有的到最下面。

**Comment by zwxbest** [comment]
可以了

在  initArticle方法的setTimeout之前加上window.scroll(window.scrollX,0);

不过还是不清楚为什么为出现这种情况，希望V大能解惑。

**Comment by Vanessa219** [comment]
pjax 并没有对页面进行刷新，只是替换了 DOM，所以滚动条位置没有变。我在统一的方法里面加了。你可以更新最新代码并移除你的方法了。 😊
