### ISSUE TITLE
91PHP 能否考虑增加分享

### ISSUE THREAD

**Issue by BaLaLaLs** [b3log/solo-skins#30]
### 你在什么场景下需要该功能？

讲编写的文章分享到朋友圈或者qq空间时需要

### 描述可能的解决方案

就像Pinghsu  那样下方漂浮一排按钮

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by Vanessa219** [comment]
该皮肤没有浮层设计，置于以下红框位置如何？

![image](https://user-images.githubusercontent.com/970828/65301543-9c9d7980-dbaa-11e9-9b3b-12bb104f888f.png)

**Comment by BaLaLaLs** [comment]
个人感觉可以
